### ISSUE TITLE
Database Strings not Appearing in the UI

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#1]
The fields "Name of Highest Paid Employee" and "Title of Highest Paid Employee" contain text data, but show up as 0 on the user interface.  This appears to be a problem with applying numeral.js.  Perhaps strings should be excluded from numeral.js processing.

We are using numeral.js to apply "masks" listed in the Fusion table to format numeric outputs (such as decimals and percentages).

**Comment by damoncasale** [comment]
Very simple way to take care of this.  Simply take the masks out of the masks column on the fusion table for those columns.

**Comment by joffemd** [comment]
The two fields I referenced don't have masks, so I believe this is a bug.

**Comment by joffemd** [comment]
An additional issue with our numeral,js implementation is that it is not properly handing percentages.  If I provide the string 0.00% I am only seeing an integer with no percentage sign.
