### ISSUE TITLE
Remaining Cosmetic Issues with Financial Statements

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#10]
We need to display column headers above Revenues.  These are General Fund. Other Funds, and Total Governmental Funds.

Amounts should be right justified and rounded to the nearest dollar (i.e., zero decimal places)

**Comment by ghost** [comment]
- and trailing zeroes
- from Overview subheading
- Column Headers 
- cleaned up visual reresentaion of data - bold subheaders, more space, removed italics from fonts
