### ISSUE TITLE
Ability to Get to a Specific Government's Web Page Directly by URL

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#12]
We need to have the ability to enter URLs like this:

http://www.govwiki.us?gov_name=CITY%20OF%20TUSTIN
http://www,govwiki,us?_id=4109

and go directly to the Tustin page.

Vadim says:  Showing the right page by id is called routing. There are several ways to add this feature.  Bootstrap way, HTML5 way etc

**Comment by vadim-ivlev** [comment]
I guess I've replied already. We are using prebuilt Dreamfactory REST API
on the server side. So we cannot use URLs like
http://www.govwiki.us?gov_name=CITY%20OF%20TUSTIN
http://www.govwiki.us/?gov_name=CITY%20OF%20TUSTIN.
The standard way to solve the problem is to use client side routing.

**Comment by joffemd** [comment]
Sorry I am not familiar with client side routing.  If we use that, what would the user have to do to directly reach a particular city without going through the search?

**Comment by vadim-ivlev** [comment]
The user will not have to do anything special. The URL of the Tustin page
will look like:

http://www.govwiki.us/#4104

Or if we want to remember the state of the page, for example the opened tab
or scroll position etc, we can do something like:

http://www.govwiki.us/#_id=4104&tab=tab_name

The only difference in URLs actually is that '#' is used instead of '?'

**Comment by vadim-ivlev** [comment]
Everything what goes after the hash # can be used by the client code to do
some things. This part of the code is not analyzed by the  server.

**Comment by vadim-ivlev** [comment]
I meant the part of the URL residing after # is not analyzed by the server,
and can be used exclusively in the browser to show a proper page.

**Comment by vadim-ivlev** [comment]
HTML5 has History API do such things if we are not using third party
frameworks. Frameworks such as AngularJS, Meteor etc. have their own ways
to do client side routing.

**Comment by joffemd** [comment]
Thanks, Vadim. I am fine with hash signs (#) in the URL.  

David:  It is not necessary to implement direct navigation to a particular tab at this time.  We just need the ability to directly reach the first tab for any given government.
