### ISSUE TITLE
Change to fields being used by the charts in Employee Compensation

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#14]
On Wednesday, I added two fields and renamed one field that will affect the charts in the Employee Compensation. I did this to make the field names more understandable and to meet the client's request for stacked bar charts showing a distinction between wages and benefits.

Chart 1 - Left stack:  median_salary_per_ft_employee, median_benefits_per_ft_employee
    Right stack:  median_wages_general_public , median_benefits_general_public

Chart 2 - Left stack: median_pension_30_year_retiree (only one column for this "stack")
    Right stack:   median_wages_general_public , median_benefits_general_public

**Comment by ghost** [comment]
`median_salary_per_ft_employee, median_benefits_per_ft_employee` does not show data yet
fot the time being the chart is loaded with `median_salary_per_full_time_emp , median_benefits_per_ft_emp` 
i susspect it has something to do with the [fusiontable](https://www.google.com/fusiontables/DataSource?docid=1z2oXQEYQ3p2OoMI8V5gKgHWB5Tz990BrQ1xc1tVo#rows:id=1)
