### ISSUE TITLE
Add links to Wikipedia and TransparentCalifornia Pages

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#19]
I have added two new columns to the govs table:  

wikipedia_page_name
transparent_california_page_name

I have populated these for cities and counties in California with URLs pointing to the appropriate content.

Please add icons at the top right of each entity page of govwiki linking to this content.  For now, the pages should come up in a new browser tab.  We may try an IFrame at some point.

A Wikipedia logo can be found here:  http://www.mailamengg.com/Portals/0/photo1/logo/wikipedia.png

Transparent California does not have a logo.  Use this as a placeholder for now http://us.cdn2.123rf.com/168nwm/blankstock/blankstock1409/blankstock140900218/31369868-text-edit-sign-icon-letter-t-button-circle-flat-button-with-shadow-modern-ui-website-navigation-vect.jpg

**Comment by vadim-ivlev** [comment]
Added links to wikipedia page.

**Comment by vadim-ivlev** [comment]
Added a link to Transparent California page.
