### ISSUE TITLE
Cosmetic Improvements to the Employee Compensation,Quality of Services and Financial HealthTabs

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#2]
All field outputs should be arranged in a single column.  I suggest outputting the entire left side as a table, so that columns automatically align.

Also, the graphs are too large and unattractive.  These need to be fixed.

**Comment by joffemd** [comment]
Most issues have been resolved, but the graphs still need to be replaced.

**Comment by ghost** [comment]
changed flot library for google charts library to draw graphs/charts
