### ISSUE TITLE
Elected Official Phone Numbers

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#20]
In some cases we have populated column elected_officials.telephone_number.  If this field is not null, it should be displayed after email address.

**Comment by bhattkrishna19** [comment]
I have added this key to show details. I am not sure how to test this. for most of the cases its coming as null.

**Comment by joffemd** [comment]
To KB:  Looks good for _id 4014. One minor issue:  please insert one space between the string "Telephone Number:" and the number itself.

**Comment by bhattkrishna19** [comment]
this is done.
