### ISSUE TITLE
Home Page Should Be Accessible from http://civicprofiles.californiapolicycenter.org/ 

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#36]
It would also be nice if govwiki.us continued to work, but the new URL is more important.  Client side routing by _id and alt_name should continue to be available from the new URL.

Our client's consultant recommends the following:

Change the CNAME file to include the string civicprofiles.californiapolicycenter.org

I believe you're going to want to upload it here: https://github.com/govwiki/govwiki.github.io

He also writes:

I created a CNAME in the californiapolicycenter.org DNS records called "civicprofiles". That record points to: govwiki.github.io

So, if I understand things correctly... http://civicprofiles.californiapolicycenter.org/ is supposed to land on your project that will eventually be visible at http://govwiki.github.io

**Comment by sibers-voronov** [comment]
I upload all files to https://github.com/govwiki/govwiki.github.io repo, and change CNAME to civicprofiles.californiapolicycenter.org but it seems don't working for now. Please check if you need something else

**Comment by igor-po** [comment]
Hello Marc,

I hope you are doing well!

Please let me inform you that we've checked the cname issue and the accompanying documentation and found the reason.

As we can see in the Github documentation, there is only one URL can be added to the cname file.
That means, we can have only one demo version can be under the code.

Thus, we can see only two solutions:
1) Place the staging server in another place and have the demos under both current http://civicprofiles.californiapolicycenter.org/ URLs.
2) Close the current demo and move it to http://civicprofiles.californiapolicycenter.org/

Please let me know what you think about it?

Thank you in advance.

Igor

**Comment by joffemd** [comment]
Let's try option 2.

**Comment by igor-po** [comment]
Hello Marc,

OK, we will do it shortly.

Could you please add one more our developer to GitHub project?
His username is valerymakarenko

Thank you in advance.

Igor

2015-07-27 20:12 GMT+06:00 Marc Joffe notifications@github.com:

**Comment by joffemd** [comment]
I made the update myself.
