### ISSUE TITLE
Ability to Create and Control Section Headers from the Fusion Table

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki-dev.us#4]
The Fusion Table contains most of the fields appearing in the UI, however we also need this table to hold section headers - bolded and potentially larger text that will be displayed without field content.

Right now that functionality is not working.  We need to be able to enter rows in the Fusion table that do not have field names and are thus understood to be labels only.  These labels may contain HTML tags such as <B>Bold</B>and <I>Italic</I> which should be respected by the UI code.

**Comment by ghost** [comment]
you can now add subheaders by altering the [fusiontable](https://www.google.com/fusiontables/DataSource?docid=1z2oXQEYQ3p2OoMI8V5gKgHWB5Tz990BrQ1xc1tVo#rows:id=1)  like so :

| general category | field_name | description | city | cty | ... | mask |
| --- | --- | --- | --- | --- | --- | --- |
| Employee Compensation | Other Post Retirement Benefits Data (Helathcare, etc.) | Other Post Retirement Benefits Data (Helathcare, etc.) | x |  | ... | heading |
|  | this column doesnt matter, but must be UNIQUE | This Column Is displayed | !!X's where you want to dispaly headings |  | ... | heading options |

heading options are 
- heading
- heading_bold
- heading_italic
- heading_bold_italic
